GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhbm55IiwicGFzc3dvcmQiOiIkMmIkMTAkRC9mcHl5bEluLjI2cm12TDBDTTh2TzV0d0N2UVFNdnRhNjJRaC5sZzR6LjZieC5PWm8zSkciLCJpYXQiOjE2ODQ1MTcxOTMsImV4cCI6MTY4NDUxNzQ5M30.fiZT_EMeWH0GJM9lrTkDXEhZNStiDjm6N5A4vpNWN-k

###

POST http://localhost:3000/create-user
Content-Type: application/json

{
    "username": "Danny",
    "password": "secret"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Danny",
    "password": "secret"
}

###

POST http://localhost:3000/refreshToken 
Content-Type: application/json



###

GET http://localhost:3000/logout

###

GET http://localhost:3000/cookies

###